version: '3'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    restart: always
    container_name: "calendar-web"
    volumes:
      - .:/app
    environment:
        - POSTGRES_URL=database
        - POSTGRES_URL_TEST=calendar-test
        - POSTGRES_URL_PROD=calendar
        - POSTGRES_USER=calendar
        - POSTGRES_PASSWORD=8c3c4b9295a3ea5f01405e0bd29c814e
        - RAILS_ENV=production
        - EDITOR="mate --wait"
    depends_on:
      - database

  database:
    image: postgres:12.11-alpine
    restart: always
    environment:
      - POSTGRES_USER=calendar
      - POSTGRES_PASSWORD=8c3c4b9295a3ea5f01405e0bd29c814e
